services:
  wikipedia:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      - WATCHFILES_FORCE_POLLING=true
      - PYTHONDONTWRITEBYTECODE=1
    restart: always

volumes:
  model_data: